version: "3"

services:
  app:
    build:
      context: market-backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./market-backend/app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"