version: "3"

services:
  backend-srv:
    image: backend-img:latest
    build:
      context: market-backend
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./market-backend/app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword

  frontend-srv:
    image: frontend-img:latest
    build:
      context: market-frontend
      dockerfile: ./Dockerfile
    ports:
      - "4200:4200"